### ISSUE TITLE
[Forked due unattended]

### ISSUE THREAD

**Issue by busslina** [desktop-dart/duration#69]
https://github.com/busslina/dart-duration

Corrected some bugs

Include snippet:
```yaml
dependencies:
  duration:
      git:
        url: https://github.com/busslina/dart-duration.git
        ref: master
```
